package com.miguel_damasco.DoSafe.document.dto.mapper;

import java.util.List;

import org.springframework.data.domain.Page;

import com.miguel_damasco.DoSafe.document.domain.DocumentModel;
import com.miguel_damasco.DoSafe.document.dto.response.DocumentPageResponseDTO;
import com.miguel_damasco.DoSafe.document.dto.response.DocumentSummaryResponseDTO;
import com.miguel_damasco.DoSafe.document.dto.response.DocumentUploadResponseDTO;

public class DocumentResponseMapper {

    public static DocumentUploadResponseDTO toDto(DocumentModel pDocument) {

        return new DocumentUploadResponseDTO(pDocument.getId().toString(),
                                             pDocument.getType().name(),
                                             pDocument.getOriginalFilename(),
                                             pDocument.getCreatedAt(),
                                             pDocument.getExpireAt());
    }

    // Maps a single DocumentModel to the summary DTO used in list responses.
    // 'type' may be null while OCR is still running, so we guard with a null check.
    // 'pDownloadUrl' is generated by the service before calling this method and
    // passed in — the mapper has no knowledge of S3 or how URLs are produced.
    public static DocumentSummaryResponseDTO toSummaryDto(DocumentModel pDocument, String pDownloadUrl) {

        String type = pDocument.getType() != null ? pDocument.getType().name() : null;

        return new DocumentSummaryResponseDTO(pDocument.getId().toString(),
                                              type,
                                              pDocument.getStatus().name(),
                                              pDocument.getOriginalFilename(),
                                              pDocument.getCreatedAt(),
                                              pDocument.getExpireAt(),
                                              pDownloadUrl);
    }

    // Converts a Spring Data Page into the paginated DTO the controller returns.
    // pUrlResolver is a function that takes a DocumentModel and returns its presigned
    // download URL. Passing it as a parameter keeps the mapper free of infrastructure
    // dependencies (S3, storage layer) while still allowing each document to carry its URL.
    public static DocumentPageResponseDTO toPageDto(Page<DocumentModel> pPage,
                                                    java.util.function.Function<DocumentModel, String> pUrlResolver) {

        List<DocumentSummaryResponseDTO> content = pPage.getContent()
                .stream()
                .map(doc -> toSummaryDto(doc, pUrlResolver.apply(doc)))
                .toList();

        return new DocumentPageResponseDTO(content,
                                           pPage.getNumber(),
                                           pPage.getSize(),
                                           pPage.getTotalElements(),
                                           pPage.getTotalPages(),
                                           pPage.isLast());
    }

    private DocumentResponseMapper() {}
}
